/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canonodesign;

import java.awt.Color;
import INTERNALPAGES.*;
import INTERNALPAGES.DashboardPage;
/**
 *
 * @author canono
 */
public class dashboards extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboards() {
        initComponents();
        
         DashboardPage dbp = new DashboardPage();
        maindesktop.add(dbp).setVisible(true);
    }
 Color navcolor = new Color(0,153,255);
 Color headcolor = new Color(0,204,204);
 Color bodycolor = new Color(204,255,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        DASH = new javax.swing.JPanel();
        DASHBOARD = new javax.swing.JLabel();
        USERPANE = new javax.swing.JPanel();
        USER = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        USER1 = new javax.swing.JLabel();
        REPORTS1 = new javax.swing.JPanel();
        USER2 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        maindesktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        navbar.setBackground(new java.awt.Color(0, 153, 255));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DASH.setBackground(new java.awt.Color(0, 153, 255));
        DASH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DASHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DASHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DASHMouseExited(evt);
            }
        });
        DASH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DASHBOARD.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        DASHBOARD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DASHBOARD.setText("DASHBOARD");
        DASH.add(DASHBOARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        navbar.add(DASH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 30));

        USERPANE.setBackground(new java.awt.Color(0, 153, 255));
        USERPANE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                USERPANEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                USERPANEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                USERPANEMouseExited(evt);
            }
        });
        USERPANE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USER.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        USER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER.setText("USER PAGE");
        USERPANE.add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        navbar.add(USERPANE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 120, 30));

        account.setBackground(new java.awt.Color(0, 153, 255));
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountMouseExited(evt);
            }
        });
        account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USER1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        USER1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER1.setText("ACCOUNT");
        account.add(USER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 30));

        navbar.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 120, 30));

        REPORTS1.setBackground(new java.awt.Color(0, 153, 255));
        REPORTS1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                REPORTS1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                REPORTS1MouseExited(evt);
            }
        });
        REPORTS1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USER2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        USER2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER2.setText("DISPLAY RECORDS");
        REPORTS1.add(USER2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        navbar.add(REPORTS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 120, 30));

        jPanel1.add(navbar);
        navbar.setBounds(0, 0, 120, 380);

        header.setBackground(new java.awt.Color(204, 255, 255));
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerMouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addGap(18, 18, 18))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel1.add(header);
        header.setBounds(120, 0, 530, 40);

        maindesktop.setBackground(new java.awt.Color(0, 204, 204));
        maindesktop.setPreferredSize(new java.awt.Dimension(547, 376));

        javax.swing.GroupLayout maindesktopLayout = new javax.swing.GroupLayout(maindesktop);
        maindesktop.setLayout(maindesktopLayout);
        maindesktopLayout.setHorizontalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        maindesktopLayout.setVerticalGroup(
            maindesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(maindesktop);
        maindesktop.setBounds(120, 40, 530, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DASHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASHMouseEntered
        DASH.setBackground(bodycolor);
    }//GEN-LAST:event_DASHMouseEntered

    private void DASHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASHMouseExited
        DASH.setBackground(navcolor);
    }//GEN-LAST:event_DASHMouseExited

    private void USERPANEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USERPANEMouseEntered
       USERPANE.setBackground(bodycolor);
    }//GEN-LAST:event_USERPANEMouseEntered

    private void USERPANEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USERPANEMouseExited
       USERPANE.setBackground(navcolor);
    }//GEN-LAST:event_USERPANEMouseExited

    private void accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseEntered
        account.setBackground(bodycolor);
    }//GEN-LAST:event_accountMouseEntered

    private void accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseExited
        account.setBackground(navcolor);
    }//GEN-LAST:event_accountMouseExited

    private void USERPANEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USERPANEMouseClicked
        USERPAGE up = new USERPAGE();
        maindesktop.add(up).setVisible(true);
    }//GEN-LAST:event_USERPANEMouseClicked

    private void headerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseClicked
   

    }//GEN-LAST:event_headerMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
            
System.exit(0);

    }//GEN-LAST:event_exitMouseClicked

    private void DASHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASHMouseClicked
        DashboardPage dbp = new DashboardPage();
        maindesktop.add(dbp).setVisible(true);
    }//GEN-LAST:event_DASHMouseClicked

    private void REPORTS1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REPORTS1MouseEntered
       REPORTS1.setBackground(bodycolor);
    }//GEN-LAST:event_REPORTS1MouseEntered

    private void REPORTS1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REPORTS1MouseExited
          REPORTS1.setBackground(navcolor);
    }//GEN-LAST:event_REPORTS1MouseExited

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
         settingsPage set = new  settingsPage();
        maindesktop.add(set).setVisible(true);
    }//GEN-LAST:event_accountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DASH;
    private javax.swing.JLabel DASHBOARD;
    private javax.swing.JPanel REPORTS1;
    private javax.swing.JLabel USER;
    private javax.swing.JLabel USER1;
    private javax.swing.JLabel USER2;
    private javax.swing.JPanel USERPANE;
    private javax.swing.JPanel account;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane maindesktop;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel navbar;
    // End of variables declaration//GEN-END:variables
}
